name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run:  echo "Hello  World!"
      - name: Print good buy
        run: echo "Done - bye!"
  
