name: esp platform workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v5.2.1 --recursive https://github.com/espressif/esp-idf.git
          cd ~/esp/esp-idf
          ./install.sh esp32
          . ~/esp/esp-idf/export.sh
          cd $GITHUB_WORKSPACE
          idf.py build
          echo "Hello  World!"
          echo "Done - bye!"
